## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# check for any missing values in the data
attrition_df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]

y_df.head()



Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [37]:
#find out how many unique values are in the Attrition column and the Department columns.

print(y_df['Attrition'].value_counts())
print(y_df['Department'].value_counts())

Attrition
No     1233
Yes     237
Name: count, dtype: int64
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64


In [24]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    "Age",
    "NumCompaniesWorked",
    "DistanceFromHome",
    "TrainingTimesLastYear",
    "HourlyRate",
    "YearsSinceLastPromotion",
    "JobSatisfaction",
    "TotalWorkingYears",
    "YearsAtCompany",
    "PercentSalaryHike",
    "YearsInCurrentRole"]


# Create X_df using your selected columns
X_df = attrition_df[selected_columns]



# Show the data types for X_df and the shape
print(X_df.dtypes)
print(X_df.shape)


Age                        int64
NumCompaniesWorked         int64
DistanceFromHome           int64
TrainingTimesLastYear      int64
HourlyRate                 int64
YearsSinceLastPromotion    int64
JobSatisfaction            int64
TotalWorkingYears          int64
YearsAtCompany             int64
PercentSalaryHike          int64
YearsInCurrentRole         int64
dtype: object
(1470, 11)


In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=78)




In [7]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# NOT NEEDED FOR THE FEATURES I CHOSE BUT IF I DID I WOULD USE:
# X_train = X_train.apply(pd.to_numeric)
# X_test = X_test.apply(pd.to_numeric)



In [8]:
# Create a StandardScaler
from sklearn.preprocessing import StandardScaler


# Fit the StandardScaler to the training data
X_scaler = StandardScaler().fit(X_train)


# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



In [26]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder

# Fit the encoder to the training data
enc = OneHotEncoder(sparse_output=False, handle_unknown="ignore", drop=None)
enc.fit(np.array(y_train["Department"]).reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data

y_train_department = enc.transform(np.array(y_train["Department"]).reshape(-1, 1))
y_test_department = enc.transform(np.array(y_test["Department"]).reshape(-1, 1))

print(y_train_department)
print(y_test_department)


[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# Create a OneHotEncoder for the Attrition column
enc = OneHotEncoder(sparse_output=False)


# Fit the encoder to the training data
enc.fit(np.array(y_train["Attrition"]).reshape(-1, 1))


# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition = enc.transform(np.array(y_train["Attrition"]).reshape(-1, 1))
y_test_attrition = enc.transform(np.array(y_test["Attrition"]).reshape(-1, 1))

print(y_train_attrition)
print(y_test_attrition)



[[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0.

## Create, Compile, and Train the Model

In [28]:
# Find the number of columns in the X training data
input_features = len(X_train_scaled[0])


# Create the input layer
input_features = len(X_train_scaled[0])
inputs = layers.Input(shape=input_features,name="inputs")


# Create at least two shared layers
shared_1 = layers.Dense(units=64, activation='relu', name="shared_1")(inputs)
shared_2 = layers.Dense(units=128, activation='relu', name="shared_2")(shared_1)


In [12]:
print(inputs)
print(shared_1)
print(shared_2)

KerasTensor(type_spec=TensorSpec(shape=(None, 11), dtype=tf.float32, name='inputs'), name='inputs', description="created by layer 'inputs'")
KerasTensor(type_spec=TensorSpec(shape=(None, 64), dtype=tf.float32, name=None), name='shared_1/Relu:0', description="created by layer 'shared_1'")
KerasTensor(type_spec=TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), name='shared_2/Relu:0', description="created by layer 'shared_2'")


In [13]:
y_train_department.shape[1]

3

In [29]:
# Create a branch for Department with a hidden layer and an output layer

department_hidden = layers.Dense(units=32, activation='softmax', name='department_hidden')(shared_2)
department_output = layers.Dense(units=3, activation='softmax', name='department_output')(department_hidden)




In [15]:
y_train_attrition.shape[1]

2

In [30]:
# Create a branch for Attrition with a hidden layer and an output layer

attrition_hidden = layers.Dense(units=32, activation='softmax', name='attrition_hidden')(shared_2)
attrition_output = layers.Dense(units=2, activation='softmax', name='attrition_output')(attrition_hidden)






In [31]:
# Create the model
model = Model(inputs=inputs, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'categorical_crossentropy'},
              metrics={"department_output":'accuracy', "attrition_output":'accuracy'})

# Summarize the model
model.summary()




Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 inputs (InputLayer)         [(None, 11)]                 0         []                            
                                                                                                  
 shared_1 (Dense)            (None, 64)                   768       ['inputs[0][0]']              
                                                                                                  
 shared_2 (Dense)            (None, 128)                  8320      ['shared_1[0][0]']            
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared_2[0][0]']            
                                                                                            

In [32]:
# Train the model
model.fit(X_train_scaled, {'department_output': y_train_department, 'attrition_output': y_train_attrition}, epochs=100, shuffle=True, verbose=2)





Epoch 1/100
35/35 - 2s - loss: 1.6455 - department_output_loss: 1.0494 - attrition_output_loss: 0.5961 - department_output_accuracy: 0.5436 - attrition_output_accuracy: 0.8276 - 2s/epoch - 43ms/step
Epoch 2/100
35/35 - 0s - loss: 1.4184 - department_output_loss: 0.9041 - attrition_output_loss: 0.5142 - department_output_accuracy: 0.6661 - attrition_output_accuracy: 0.8276 - 74ms/epoch - 2ms/step
Epoch 3/100
35/35 - 0s - loss: 1.3539 - department_output_loss: 0.8716 - attrition_output_loss: 0.4824 - department_output_accuracy: 0.6661 - attrition_output_accuracy: 0.8276 - 74ms/epoch - 2ms/step
Epoch 4/100
35/35 - 0s - loss: 1.3249 - department_output_loss: 0.8539 - attrition_output_loss: 0.4709 - department_output_accuracy: 0.6661 - attrition_output_accuracy: 0.8276 - 74ms/epoch - 2ms/step
Epoch 5/100
35/35 - 0s - loss: 1.3059 - department_output_loss: 0.8398 - attrition_output_loss: 0.4661 - department_output_accuracy: 0.6661 - attrition_output_accuracy: 0.8276 - 74ms/epoch - 2ms/step
E

In [33]:


# Evaluate the model with the testing data
evaluation_results = model.evaluate(X_test_scaled, {'department_output': y_test_department, 'attrition_output': y_test_attrition}, verbose=2)

# Print the evaluation results
print("Evaluation results:", evaluation_results)



12/12 - 0s - loss: 1.4113 - department_output_loss: 0.9725 - attrition_output_loss: 0.4388 - department_output_accuracy: 0.5679 - attrition_output_accuracy: 0.8261 - 279ms/epoch - 23ms/step
Evaluation results: [1.4112869501113892, 0.972507119178772, 0.43877992033958435, 0.5679348111152649, 0.8260869383811951]


In [34]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {evaluation_results[3]*100}")
print(f"Attrition Accuracy: {evaluation_results[4]*100}")

Department Accuracy: 56.79348111152649
Attrition Accuracy: 82.6086938381195


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Because this dataset is imbalanced, meaning that one class in each y feature (no attrition; Research & Development) is much more prevalent than the other (attrition; Sales, Human Resources), accuracy alone can be misleading. A model that simply predicts the majority class for all instances could achieve high accuracy, but it would not be useful in practice.
We would also want to look at the business context. For example, if the primary goal were to identify employees at risk of leaving in order to intervene and retain them, a model with high recall (minimizing false negatives) would be more valuable, even if it sacrifices some precision.
2. I started with the reLu activation for the shared and hidden layers with Softmax only in the output layer of the y data, because ReLU is a common choice for activation functions in the input and hidden layers of neural networks due to its simplicity, efficiency, and effectiveness in learning complex representations from data. However, the model wasn't performing super well so I decided to retain reLu in the shared layers, but try Softmax across the hidden layers in addition to the output layers. Softmax activation is primarily used in the output layer of neural networks for multi-class classification tasks. It's particularly useful when you have more than two classes in your target variable. In this case, it helped the model to perform even better when it was used across the hidden and output layers.
3. I did improve the model by trying different activation methods; one could also add more layers or neurons, hyperparameter tuning with learning rate, batch size, number of epochs, optimizer choice, etc.; or try feature engineering, and search for biases in the data to balance them.